apiVersion: v1
kind: ServiceAccount
metadata:
  name: blast-radius
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: "{{ .Values.aws.roleArn }}"
    # Example: arn:aws:iam::123456789012:role/BlastRadiusRole
automountServiceAccountToken: true