apiVersion: v2
name: blast-radius
description: A Helm chart for Blast Radius - Interactive Terraform Graph Visualizations with S3 and IRSA support
type: application
version: 0.1.0
appVersion: "0.1.25"
keywords:
  - terraform
  - visualization
  - aws
  - s3
  - irsa
home: https://github.com/nkbud/blast-radius
sources:
  - https://github.com/nkbud/blast-radius
maintainers:
  - name: nkbud
    email: ""