apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blast-radius.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blast-radius.labels" . | nindent 4 }}
data:
  S3_REGION: "{{ .Values.s3.region }}"
  STATE_REFRESH_INTERVAL: "{{ .Values.s3.refreshInterval }}"
  BLAST_RADIUS_PORT: "5000"