apiVersion: v1
kind: Service
metadata:
  name: {{ include "blast-radius.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "blast-radius.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    {{- include "blast-radius.selectorLabels" . | nindent 4 }}